# Generated by Django 3.2.13 on 2022-04-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220427_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
