# Generated by Django 3.2.13 on 2022-04-27 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220427_1903'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
