# Generated by Django 3.2.13 on 2022-04-27 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.artist'),
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
