# Generated by Django 3.2.13 on 2022-04-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_artist_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablespaceExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, db_tablespace='indexes', max_length=30)),
                ('data', models.CharField(db_index=True, max_length=255)),
                ('shortcut', models.CharField(max_length=7)),
                ('edges', models.ManyToManyField(db_tablespace='indexes', related_name='_app_tablespaceexample_edges_+', to='app.TablespaceExample')),
            ],
        ),
    ]
