# Generated by Django 3.2.13 on 2022-04-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_tablespaceexample'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tablespaceexample',
            index=models.Index(db_tablespace='other_indexes', fields=['shortcut'], name='app_tablesp_shortcu_c956e5_idx'),
        ),
    ]
