# Generated by Django 3.2.13 on 2022-04-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_tablespaceexample_app_tablesp_shortcu_c956e5_idx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TablespaceExample',
        ),
    ]
