# Generated by Django 3.2.13 on 2022-04-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_tablespaceexample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
