# Generated by Django 3.2.13 on 2022-04-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220428_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='age',
            field=models.CharField(blank=True, db_column='age1', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
