# Generated by Django 3.2.13 on 2022-04-28 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_album_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique_for_date='created')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('suspended', 'Suspended')], default='draft', max_length=15)),
                ('content', models.TextField(blank=True, max_length=200000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.DateTimeField(default=datetime.datetime(2022, 4, 28, 6, 14, 16, 699431, tzinfo=utc))),
            ],
        ),
    ]
