# Generated by Django 3.2.13 on 2022-04-28 06:45

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even_field', models.IntegerField(validators=[app.models.validate_even])),
            ],
        ),
    ]
