# Generated by Django 3.2.13 on 2022-04-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_mymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
