# Generated by Django 3.2.13 on 2022-04-28 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_mymodel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='id',
            new_name='roll_no',
        ),
    ]
