# Generated by Django 3.2.13 on 2022-04-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_mymodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
