# Generated by Django 3.2.13 on 2022-04-28 07:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20220428_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='uiid2',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
