# Generated by Django 3.2.13 on 2022-04-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_rename_artist_album_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album',
            new_name='artist',
        ),
    ]
