# Generated by Django 3.2.13 on 2022-05-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_mymodel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='_in',
            field=models.DateTimeField(help_text='When the cow got back IN FROM Pasture.', null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='out',
            field=models.DateTimeField(help_text='When the cow went OUT TO Pasture.', null=True),
        ),
    ]
