# Generated by Django 3.2.13 on 2022-05-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_merge_0039_auto_20220511_1315_0039_auto_20220511_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='_in',
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='out',
        ),
    ]
