# Generated by Django 3.2.13 on 2022-05-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20220511_1427'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='mymodel',
    #         name='duration',
    #     ),
    # ]
