# Generated by Django 3.2.13 on 2022-05-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_mymodel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='duration',
            field=models.DurationField(default=1),
            preserve_default=False,
        ),
    ]
