# Generated by Django 3.2.13 on 2022-06-08 09:27

import app.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220427_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('out', models.DateTimeField(help_text='When the cow went OUT TO Pasture.', null=True)),
                ('_in', models.DateTimeField(help_text='When the cow got back IN FROM Pasture.', null=True)),
                ('duration', models.DurationField()),
                ('even_field', models.IntegerField(validators=[app.models.validate_even])),
                ('uiid1', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('uiid2', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique_for_year='publish')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('suspended', 'Suspended')], default='draft', max_length=15)),
                ('content', models.TextField(blank=True, max_length=200000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='age',
            field=models.CharField(blank=True, db_column='age1', max_length=100, null=True),
        ),
    ]
