# Generated by Django 3.2.13 on 2022-06-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220608_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
