# Generated by Django 3.2.13 on 2022-06-08 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_mymodel_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
