# Generated by Django 3.2.13 on 2022-06-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_mymodel_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
